name: 'setup node'
description: 'Setup Node'
runs:
  using: 'composite'
  steps:
    - name: Enable Corepack
      shell: bash
      run: corepack enable

    - name: Set up Node
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version-file: '.nvmrc'
        cache: 'yarn'
        cache-dependency-path: yarn.lock
