name: 'setup node'
description: 'Setup Node'
runs:
  using: 'composite'
  steps:
    - name: Enable Corepack
      shell: bash
      run: corepack enable

    - name: Set up Node
      uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
      with:
        node-version-file: '.nvmrc'
        cache: 'yarn'
        cache-dependency-path: yarn.lock
