name: 'setup node'
description: 'Setup Node'
runs:
  using: 'composite'
  steps:
    - name: Enable Corepack
      shell: bash
      run: corepack enable

    - name: Set up Node
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
      with:
        node-version-file: '.nvmrc'
        cache: 'yarn'
        cache-dependency-path: yarn.lock
