name: 'setup and install'
description: 'Setup Node and Install Dependencies'
runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: ./.github/actions/setup-node

    - name: Restore cached node_modules
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      shell: bash
      run: make install
