name: 'setup and install'
description: 'Setup Node and Install Dependencies'
runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: ./.github/actions/setup-node

    - name: Restore cached node_modules
      uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      shell: bash
      run: make install
