name: Deploy
on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Fetch tags
        run: git fetch --tags origin release

      # set up git since we will later push to the repo
      - run: git config --global user.name "GitHub CI bot"
      - run: git config --global user.email "github-ci-bot@example.com"

      - run: make install

      - name: Authenticate npm
        run: ./bin/ci/npm-auth.sh
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Release
        run: make publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Merge release
        run: ./bin/ci/sync-release.sh
        if: success()
        env:
          # The secret is passed automatically. Nothing to configure.
          github-token: ${{ secrets.GITHUB_TOKEN }}
