name: 🔍 Git Checks

on: [pull_request]

jobs:
  block-fixup-merge:
    name: 🚫 Merge Blocked by Git Fixup
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Block Fixup Commit Merge
        uses: 13rac1/block-fixup-merge-action@v2.0.0
